### ISSUE TITLE
How about publishing your Plug-Ins on apex.world -> Plug-Ins?

### ISSUE THREAD

**Issue by cczarski-de** [darklordgrep/Mapbits#1]
this is an awesome collection of Plug-Ins for the map region - I could see a lot of APEX developers wanting to use them. Did you know that there is a community-driven APEX community site (https://apex.world/) ...?
There is also a Plug-In repository, where you can advertise your Plug-Ins and make them visible to the community. Basically you'd only need to provide a manifest file and publish that on apex.world - all your Plug-In files would stay where they are. All of the world-wide APEX developer community is active on that site ...

What do you think?

**Comment by darklordgrep** [comment]
Sure. Added to apex.world in March 2023.
